//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace NewAsiaOASystem.Web.Newasia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="XYOfferSoap", Namespace="http://tempuri.org/")]
    public partial class XYOffer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsrInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOfferOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderByOrderCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderShipInfoByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProvinceCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProvinceCityByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKuCunOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBomOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrderNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback WlwChargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback WlwChargeByCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public XYOffer() {
            this.Url = global::NewAsiaOASystem.Web.Properties.Settings.Default.NewAsiaOASystem_Web_Newasia_XYOffer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsrInfoCompletedEventHandler GetUsrInfoCompleted;
        
        /// <remarks/>
        public event SaveOfferCompletedEventHandler SaveOfferCompleted;
        
        /// <remarks/>
        public event GetOrdersCompletedEventHandler GetOrdersCompleted;
        
        /// <remarks/>
        public event GetOrderByIDCompletedEventHandler GetOrderByIDCompleted;
        
        /// <remarks/>
        public event GetOrderByOrderCodeCompletedEventHandler GetOrderByOrderCodeCompleted;
        
        /// <remarks/>
        public event GetOrderShipInfoByIDCompletedEventHandler GetOrderShipInfoByIDCompleted;
        
        /// <remarks/>
        public event GetNewOrdersCompletedEventHandler GetNewOrdersCompleted;
        
        /// <remarks/>
        public event GetUserProvinceCityCompletedEventHandler GetUserProvinceCityCompleted;
        
        /// <remarks/>
        public event GetUserProvinceCityByUserIdCompletedEventHandler GetUserProvinceCityByUserIdCompleted;
        
        /// <remarks/>
        public event GetUserInfoByUserIdCompletedEventHandler GetUserInfoByUserIdCompleted;
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetKuCunCompletedEventHandler GetKuCunCompleted;
        
        /// <remarks/>
        public event GetBomCompletedEventHandler GetBomCompleted;
        
        /// <remarks/>
        public event UpdateOrderNumberCompletedEventHandler UpdateOrderNumberCompleted;
        
        /// <remarks/>
        public event WlwChargeCompletedEventHandler WlwChargeCompleted;
        
        /// <remarks/>
        public event WlwChargeByCodeCompletedEventHandler WlwChargeByCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsrInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsrInfo GetUsrInfo(int id) {
            object[] results = this.Invoke("GetUsrInfo", new object[] {
                        id});
            return ((UsrInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsrInfoAsync(int id) {
            this.GetUsrInfoAsync(id, null);
        }
        
        /// <remarks/>
        public void GetUsrInfoAsync(int id, object userState) {
            if ((this.GetUsrInfoOperationCompleted == null)) {
                this.GetUsrInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsrInfoOperationCompleted);
            }
            this.InvokeAsync("GetUsrInfo", new object[] {
                        id}, this.GetUsrInfoOperationCompleted, userState);
        }
        
        private void OnGetUsrInfoOperationCompleted(object arg) {
            if ((this.GetUsrInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsrInfoCompleted(this, new GetUsrInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveOffer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveOffer(Shop_Offer model) {
            object[] results = this.Invoke("SaveOffer", new object[] {
                        model});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOfferAsync(Shop_Offer model) {
            this.SaveOfferAsync(model, null);
        }
        
        /// <remarks/>
        public void SaveOfferAsync(Shop_Offer model, object userState) {
            if ((this.SaveOfferOperationCompleted == null)) {
                this.SaveOfferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOfferOperationCompleted);
            }
            this.InvokeAsync("SaveOffer", new object[] {
                        model}, this.SaveOfferOperationCompleted, userState);
        }
        
        private void OnSaveOfferOperationCompleted(object arg) {
            if ((this.SaveOfferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOfferCompleted(this, new SaveOfferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrders(int orderId) {
            object[] results = this.Invoke("GetOrders", new object[] {
                        orderId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersAsync(int orderId) {
            this.GetOrdersAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetOrdersAsync(int orderId, object userState) {
            if ((this.GetOrdersOperationCompleted == null)) {
                this.GetOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersOperationCompleted);
            }
            this.InvokeAsync("GetOrders", new object[] {
                        orderId}, this.GetOrdersOperationCompleted, userState);
        }
        
        private void OnGetOrdersOperationCompleted(object arg) {
            if ((this.GetOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersCompleted(this, new GetOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderByID(int orderId) {
            object[] results = this.Invoke("GetOrderByID", new object[] {
                        orderId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderByIDAsync(int orderId) {
            this.GetOrderByIDAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetOrderByIDAsync(int orderId, object userState) {
            if ((this.GetOrderByIDOperationCompleted == null)) {
                this.GetOrderByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderByIDOperationCompleted);
            }
            this.InvokeAsync("GetOrderByID", new object[] {
                        orderId}, this.GetOrderByIDOperationCompleted, userState);
        }
        
        private void OnGetOrderByIDOperationCompleted(object arg) {
            if ((this.GetOrderByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderByIDCompleted(this, new GetOrderByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderByOrderCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderByOrderCode(string orderCode) {
            object[] results = this.Invoke("GetOrderByOrderCode", new object[] {
                        orderCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderByOrderCodeAsync(string orderCode) {
            this.GetOrderByOrderCodeAsync(orderCode, null);
        }
        
        /// <remarks/>
        public void GetOrderByOrderCodeAsync(string orderCode, object userState) {
            if ((this.GetOrderByOrderCodeOperationCompleted == null)) {
                this.GetOrderByOrderCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderByOrderCodeOperationCompleted);
            }
            this.InvokeAsync("GetOrderByOrderCode", new object[] {
                        orderCode}, this.GetOrderByOrderCodeOperationCompleted, userState);
        }
        
        private void OnGetOrderByOrderCodeOperationCompleted(object arg) {
            if ((this.GetOrderByOrderCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderByOrderCodeCompleted(this, new GetOrderByOrderCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderShipInfoByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOrderShipInfoByID(int orderId) {
            object[] results = this.Invoke("GetOrderShipInfoByID", new object[] {
                        orderId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderShipInfoByIDAsync(int orderId) {
            this.GetOrderShipInfoByIDAsync(orderId, null);
        }
        
        /// <remarks/>
        public void GetOrderShipInfoByIDAsync(int orderId, object userState) {
            if ((this.GetOrderShipInfoByIDOperationCompleted == null)) {
                this.GetOrderShipInfoByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderShipInfoByIDOperationCompleted);
            }
            this.InvokeAsync("GetOrderShipInfoByID", new object[] {
                        orderId}, this.GetOrderShipInfoByIDOperationCompleted, userState);
        }
        
        private void OnGetOrderShipInfoByIDOperationCompleted(object arg) {
            if ((this.GetOrderShipInfoByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderShipInfoByIDCompleted(this, new GetOrderShipInfoByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetNewOrders() {
            object[] results = this.Invoke("GetNewOrders", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewOrdersAsync() {
            this.GetNewOrdersAsync(null);
        }
        
        /// <remarks/>
        public void GetNewOrdersAsync(object userState) {
            if ((this.GetNewOrdersOperationCompleted == null)) {
                this.GetNewOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewOrdersOperationCompleted);
            }
            this.InvokeAsync("GetNewOrders", new object[0], this.GetNewOrdersOperationCompleted, userState);
        }
        
        private void OnGetNewOrdersOperationCompleted(object arg) {
            if ((this.GetNewOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewOrdersCompleted(this, new GetNewOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserProvinceCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserProvinceCity() {
            object[] results = this.Invoke("GetUserProvinceCity", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProvinceCityAsync() {
            this.GetUserProvinceCityAsync(null);
        }
        
        /// <remarks/>
        public void GetUserProvinceCityAsync(object userState) {
            if ((this.GetUserProvinceCityOperationCompleted == null)) {
                this.GetUserProvinceCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProvinceCityOperationCompleted);
            }
            this.InvokeAsync("GetUserProvinceCity", new object[0], this.GetUserProvinceCityOperationCompleted, userState);
        }
        
        private void OnGetUserProvinceCityOperationCompleted(object arg) {
            if ((this.GetUserProvinceCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProvinceCityCompleted(this, new GetUserProvinceCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserProvinceCityByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserProvinceCityByUserId(int userId) {
            object[] results = this.Invoke("GetUserProvinceCityByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProvinceCityByUserIdAsync(int userId) {
            this.GetUserProvinceCityByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetUserProvinceCityByUserIdAsync(int userId, object userState) {
            if ((this.GetUserProvinceCityByUserIdOperationCompleted == null)) {
                this.GetUserProvinceCityByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProvinceCityByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetUserProvinceCityByUserId", new object[] {
                        userId}, this.GetUserProvinceCityByUserIdOperationCompleted, userState);
        }
        
        private void OnGetUserProvinceCityByUserIdOperationCompleted(object arg) {
            if ((this.GetUserProvinceCityByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProvinceCityByUserIdCompleted(this, new GetUserProvinceCityByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserInfoByUserId(int userId) {
            object[] results = this.Invoke("GetUserInfoByUserId", new object[] {
                        userId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByUserIdAsync(int userId) {
            this.GetUserInfoByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByUserIdAsync(int userId, object userState) {
            if ((this.GetUserInfoByUserIdOperationCompleted == null)) {
                this.GetUserInfoByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByUserId", new object[] {
                        userId}, this.GetUserInfoByUserIdOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByUserIdOperationCompleted(object arg) {
            if ((this.GetUserInfoByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByUserIdCompleted(this, new GetUserInfoByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUsers(string username, string pwd) {
            object[] results = this.Invoke("GetUsers", new object[] {
                        username,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync(string username, string pwd) {
            this.GetUsersAsync(username, pwd, null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(string username, string pwd, object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[] {
                        username,
                        pwd}, this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKuCun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetKuCun(string codes, string key) {
            object[] results = this.Invoke("GetKuCun", new object[] {
                        codes,
                        key});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetKuCunAsync(string codes, string key) {
            this.GetKuCunAsync(codes, key, null);
        }
        
        /// <remarks/>
        public void GetKuCunAsync(string codes, string key, object userState) {
            if ((this.GetKuCunOperationCompleted == null)) {
                this.GetKuCunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKuCunOperationCompleted);
            }
            this.InvokeAsync("GetKuCun", new object[] {
                        codes,
                        key}, this.GetKuCunOperationCompleted, userState);
        }
        
        private void OnGetKuCunOperationCompleted(object arg) {
            if ((this.GetKuCunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKuCunCompleted(this, new GetKuCunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetBom(string bomId, string key) {
            object[] results = this.Invoke("GetBom", new object[] {
                        bomId,
                        key});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetBomAsync(string bomId, string key) {
            this.GetBomAsync(bomId, key, null);
        }
        
        /// <remarks/>
        public void GetBomAsync(string bomId, string key, object userState) {
            if ((this.GetBomOperationCompleted == null)) {
                this.GetBomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBomOperationCompleted);
            }
            this.InvokeAsync("GetBom", new object[] {
                        bomId,
                        key}, this.GetBomOperationCompleted, userState);
        }
        
        private void OnGetBomOperationCompleted(object arg) {
            if ((this.GetBomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBomCompleted(this, new GetBomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateOrderNumber(string id, string orderId) {
            object[] results = this.Invoke("UpdateOrderNumber", new object[] {
                        id,
                        orderId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrderNumberAsync(string id, string orderId) {
            this.UpdateOrderNumberAsync(id, orderId, null);
        }
        
        /// <remarks/>
        public void UpdateOrderNumberAsync(string id, string orderId, object userState) {
            if ((this.UpdateOrderNumberOperationCompleted == null)) {
                this.UpdateOrderNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrderNumberOperationCompleted);
            }
            this.InvokeAsync("UpdateOrderNumber", new object[] {
                        id,
                        orderId}, this.UpdateOrderNumberOperationCompleted, userState);
        }
        
        private void OnUpdateOrderNumberOperationCompleted(object arg) {
            if ((this.UpdateOrderNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrderNumberCompleted(this, new UpdateOrderNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WlwCharge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WlwCharge(int userId, decimal money) {
            object[] results = this.Invoke("WlwCharge", new object[] {
                        userId,
                        money});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WlwChargeAsync(int userId, decimal money) {
            this.WlwChargeAsync(userId, money, null);
        }
        
        /// <remarks/>
        public void WlwChargeAsync(int userId, decimal money, object userState) {
            if ((this.WlwChargeOperationCompleted == null)) {
                this.WlwChargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWlwChargeOperationCompleted);
            }
            this.InvokeAsync("WlwCharge", new object[] {
                        userId,
                        money}, this.WlwChargeOperationCompleted, userState);
        }
        
        private void OnWlwChargeOperationCompleted(object arg) {
            if ((this.WlwChargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WlwChargeCompleted(this, new WlwChargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WlwChargeByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WlwChargeByCode(string userCode, decimal money) {
            object[] results = this.Invoke("WlwChargeByCode", new object[] {
                        userCode,
                        money});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WlwChargeByCodeAsync(string userCode, decimal money) {
            this.WlwChargeByCodeAsync(userCode, money, null);
        }
        
        /// <remarks/>
        public void WlwChargeByCodeAsync(string userCode, decimal money, object userState) {
            if ((this.WlwChargeByCodeOperationCompleted == null)) {
                this.WlwChargeByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWlwChargeByCodeOperationCompleted);
            }
            this.InvokeAsync("WlwChargeByCode", new object[] {
                        userCode,
                        money}, this.WlwChargeByCodeOperationCompleted, userState);
        }
        
        private void OnWlwChargeByCodeOperationCompleted(object arg) {
            if ((this.WlwChargeByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WlwChargeByCodeCompleted(this, new WlwChargeByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsrInfo {
        
        private int usrIDField;
        
        private string userNameField;
        
        private string nickNameField;
        
        private string trueNameField;
        
        private string sexField;
        
        private string phoneField;
        
        private string emailField;
        
        /// <remarks/>
        public int UsrID {
            get {
                return this.usrIDField;
            }
            set {
                this.usrIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string TrueName {
            get {
                return this.trueNameField;
            }
            set {
                this.trueNameField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Shop_Offer {
        
        private int idField;
        
        private string numField;
        
        private System.Nullable<int> usrIDField;
        
        private string titleField;
        
        private System.Nullable<decimal> priceField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> usrID {
            get {
                return this.usrIDField;
            }
            set {
                this.usrIDField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUsrInfoCompletedEventHandler(object sender, GetUsrInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsrInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsrInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsrInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsrInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SaveOfferCompletedEventHandler(object sender, SaveOfferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOfferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOfferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetOrdersCompletedEventHandler(object sender, GetOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetOrderByIDCompletedEventHandler(object sender, GetOrderByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetOrderByOrderCodeCompletedEventHandler(object sender, GetOrderByOrderCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderByOrderCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderByOrderCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetOrderShipInfoByIDCompletedEventHandler(object sender, GetOrderShipInfoByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderShipInfoByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderShipInfoByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetNewOrdersCompletedEventHandler(object sender, GetNewOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUserProvinceCityCompletedEventHandler(object sender, GetUserProvinceCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProvinceCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProvinceCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUserProvinceCityByUserIdCompletedEventHandler(object sender, GetUserProvinceCityByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProvinceCityByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProvinceCityByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUserInfoByUserIdCompletedEventHandler(object sender, GetUserInfoByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetKuCunCompletedEventHandler(object sender, GetKuCunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKuCunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKuCunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetBomCompletedEventHandler(object sender, GetBomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UpdateOrderNumberCompletedEventHandler(object sender, UpdateOrderNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrderNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrderNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void WlwChargeCompletedEventHandler(object sender, WlwChargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WlwChargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WlwChargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void WlwChargeByCodeCompletedEventHandler(object sender, WlwChargeByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WlwChargeByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WlwChargeByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591